language: ruby
services:
  - postgres
rvm:
  - 2.7.2
bundler_args: --without development production doc
env:
  global:
    - TZ="Asia/Tokyo"
    - RUN_AS_ROOT=true
    - RAILS_ENV=test
    - COVERAGE_REPORTS=shippable/codecoverage
    - SMTP_FROM=test@example.com
build:
  pre_ci_boot:
    image_name: drydock/u16nodall
    image_tag: latest
    pull: true
  cache: true
  cache_dir_list:
    - /usr/local/rvm/gems/ruby-2.7.2
    - /usr/local/rvm/rubies/ruby-2.7.2
  ci:
    - echo 'Asia/Tokyo' | sudo tee /etc/timezone
    - apt remove google-chrome-stable chromium-browser
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
    - curl https://downloads.apache.org/cassandra/KEYS | sudo apt-key add -
    - rm /etc/apt/sources.list.d/basho_riak.list
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - apt update -y
    - at install -y google-chrome-stable
    - google-chrome --version
    - mkdir -p shippable/testresults
    - sudo psql -c "create database meizeimailer_test;" -U postgres
    - nvm install $(cat .node-version)
    - nvm use $(cat .node-version)
    - gem install bundler -v 2.1.4
    - bundle install $SHIPPABLE_BUNDLER_ARGS
    - bin/yarn install --frozen-lockfile
    - bundle exec rake db:schema:load
    - bundle exec rspec -f progress -f RspecJunitFormatter -o shippable/testresults/results.xml
integrations:
  - integrationName: email
    type: email
    on_success: change
    on_failure: alwaysp
