version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.2-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: ichigo
          POSTGRES_DB: postapi_test
          POSTGRES_PASSWORD: ''
    steps:
      - checkout

      - run:
          name: bundle install
          command: gem install bundler:2.1.4
      - run:
          name: update bundler
          command: bundle -v

      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: bundle isntall
          command: bundle install
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: define DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: set DB
          command: bin/rails db:schema:load --trace
      - run:
          name: rspec install
          command: bin/rails g rspec:install
      - run:
          name: rspec
          command: bundle exec rspec
      - store_test_results:
          path: test_results
